### PR TITLE
style(global): commenting code and creating readme

### LINKED ISSUE #2: Merge Berni's handover commit
Need to pull in his latest changes

### PR DESCRIPTION
**Pull request by AlexKMarshall**
Finished adding comments to the client components. Completed the readme file with instructions and
added copies of .env files for mock data

### CODE REVIEW

**Review by hucki — APPROVED** [review]
very helpful comments added by Berni. approved for merge

**Review by maylynn-ng — COMMENTED** [review]
This is fantastic work

**Comment by juansanchezlog** [comment]
Testing comment

**Review by juansanchezlog — APPROVED** [review]
Look good :)

**Review by maylynn-ng — APPROVED** [review]
Hope this is now sufficient, Hucki.

**Pull request merged**
